### ISSUE TITLE
license of the code?

### ISSUE THREAD

**Issue by moovida** [TrilogisIT/WorldWind_Android#15]
Hello developers, I can't find any reference to the license in the code of the project.

Is this released under the same NOSA as Nasa Worldwind or some other license?
Thanks.

**Comment by moovida** [comment]
I found in the example app 

```
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
```

so I assume the NWW core is NOSA and the rest Apache.

**Comment by ndorigatti** [comment]
Hello @moovida exactly, WorldWind is nasa code and follows the original license, while our code (example and FAO_Application) are under Apache2.

I'd suggest you to check also the new WorldWindAndroid repository from NASA, they are working hard to deliver a new version built from scratch!

**Comment by moovida** [comment]
Hi @ndorigatti thanks a lot for the quick reply.

I will also check the WorldWindAndroid, as you suggested, thanks!
